config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "posts#new"

  resources :posts do
    resources :comments
  end

  resources :profiles

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post
  belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, presence: true
  validates :text, presence: true

  has_many :comments, dependent: :destroy
  belongs_to :user

  self.per_page = 10

  def subject
    title
  end

  def last_comment
    comments.last
  end

  def self.search(search)
    where("title LIKE ?", "%#{search}%")
    where("text LIKE ?", "%#{search}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates_presence_of :username
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :authenticate_user!, :only =>[:create]

  def create
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id:  current_user.id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :post_owner, only: [:edit, :update, :destroy]

  def post_owner
    @post = Post.find(params[:id])
    unless @post.user_id == current_user.id
      flash[:notice] = 'Access denied as you are not owner of this post'
      redirect_to post_path
    end
  end

  def index
    @posts = Post.where(public: true).order(created_at: :desc)
    if params[:search]
      @posts = Post.where(public: true).search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all.order('created_at DESC')
    end
    @posts = @posts.paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @languages = Rails.configuration.languages
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render action: 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
    @languages = Rails.configuration.languages
  end

  def update
    @post = Post.find(params[:id])
    @languages = Rails.configuration.languages

    if @post.update(post_params)
      redirect_to @post
    else
      render action: 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    current_user == nil ? usr_id = 0 : usr_id = current_user.id
    params.require(:post).permit(:title, :text, :public, :lang).merge(user_id:  usr_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = User.all
  end

  def show

    @profile = User.find(params[:id])
    @posts = Post.where(user_id: @profile.id).order("created_at DESC")
    @posts = @posts.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shtcder</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.11.0/styles/default.min.css">
  <link href="https://fonts.googleapis.com/css?family=Finger+Paint" rel="stylesheet">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.11.0/highlight.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.6.0/clipboard.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top" role="navigation">
       <div class="container">
         <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
             <span class="sr-only">Toggle navigation</span>
           </button>
           <%= link_to 'Shtcder!', root_path, :class => "navbar-brand shtcder-brand" %>
         </div>
         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
           <ul class="nav navbar-nav">
             <li><%= link_to 'New Shtcd', new_post_path %></li>
             <li><%= link_to 'View All Shtcds', posts_path %></li>
              <%= form_tag(posts_path, :class => "navbar-form navbar-left", :method => "get", id: "search-form") do %>
                <div class="form-group">
                  <%= text_field_tag :search, params[:search], :class => "form-control", placeholder: "Search" %>
                </div>  
                <%= submit_tag "Search", :class => "btn btn-primary btn-sm" %>
              <% end %>
           </ul>
           <ul class="nav navbar-nav navbar-right">
             <li class="navbar-text notice">
               <i><%= notice %></i>
             </li>
             <li class="navbar-text alert">
               <i><%= alert %></i>
             </li>
             <% if user_signed_in? %>

              <li>
                 <div class="navbar-text">Hello, <%= link_to current_user.username, profile_path(current_user.id)%></div>
              </li>
              <li>
                   <%= link_to 'Sign Out!', destroy_user_session_path, method: :delete %>
              </li>
              <% else %>
               <li>
                 <%= link_to 'Sign In', new_user_session_path %>
               </li>
               <li>
                 <%= link_to 'Sign Up', new_user_registration_path %>
               </li>
             <% end %>
           </ul>
         </div><!--/.nav-collapse -->
       </div>
     </nav>

    <div class="container sht-container">
      <%= yield %>
    </div>
  <script>
    $(document).ready(function() {
      $('pre code').each(function(i, block) {
        hljs.highlightBlock(block);
      });
    });
  </script>
  <script>
    var clipboard = new Clipboard('.btn-clipboard');
    clipboard.on('success', function(e) {
        console.log(e);
    });
    clipboard.on('error', function(e) {
        console.log(e);
    });
  </script>
</body>
</html>

app/views/posts/_post.html.erb
  <p>
    <b><%= link_to post.title, post_path(post)%></b>
  </p>
  <p>
    <% if post.lang == 'None' %>
      <pre><code class="nohighlight"><%= post.text %></code></pre>
    <% elsif post.lang == 'Other'%>
      <pre><code><%= post.text %></code></pre>
    <%else%>
      <pre><code class="<%= post.lang.downcase%>"><%= post.text %></code></pre>
    <%end%>
  </p>
  <p>
    Author:
    <% if post.user_id == 0  %>
      Anon |
    <% else %>
      <%= link_to post.user.username, profile_path(post.user_id)%> |
    <% end %>
    Language: <%= post.lang %> |
    <%= post.created_at.strftime("%Y-%m-%d")%> |

    <%= link_to "Comments: #{post.comments.length}", post_path(post)%>
  </p>
  <hr />

app/views/posts/edit.html.erb
<div class="form-group">
  <%= form_for :post, url: post_path(@post), method: :put do |f| %>

    <p>
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control" %>
    </p>
    <p>
      <%= f.label :text%>
      <%= f.text_area :text, :class => "form-control", :rows => "7" %>
    </p>
    <p>
      <%= f.label 'Language'%>
      <%= f.select :lang, @languages %>
    </p>
    <p>
      <%= f.label :public%>
      <%= f.check_box :public%>
    </p>
    <p>
      <%= f.submit :class => "btn btn-primary" %>
    </p>
  <% end %>
</div>

app/views/posts/index.html.erb
<div id="my-posts">
  <%= render @posts %>
</div>

<div id="infinite-scrolling">
  <%= will_paginate @posts %>
</div>

app/views/posts/index.js.erb
$('#my-posts').append('<%= j render @posts %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/posts/new.html.erb
<div class="form-group">
  <%= form_for :post, url: posts_path do |f| %>

  <div class="sht-content">
    <div class="sht-title">
      <%= f.text_field :title, :class => "form-control", :placeholder => "title here"  %>
    </div>
    <div class="sht-text">
      <%= f.text_area :text, :class => "form-control", :rows => "15", :placeholder => "code here" %>
    </div>
  </div>
  <br>
  <div class="sht-content-options form-inline">

    <div class="sht-lang">
      Language:  
      <%= f.select(:lang, @languages)  %>
    </div>
    <div class="sht-publ checkbox">
      <%= f.label :public%>
      <%= f.check_box :public, :checked=>true %>
    </div>
    <div class="sht-btn">
      <%= f.submit :class => "btn btn-primary btn-sm" %>
    </div>
  </div>
  <% end %>

app/views/posts/show.html.erb
<h3><%= @post.title %></h3>
<p>
  Author:
  <% if @post.user_id == 0  %>
    Anon |
  <% else %>
    <%= link_to @post.user.username, profile_path(@post.user_id)%> |
  <% end %>
  Language: <%= @post.lang %>
</p>
<p>
  <% if @post.lang == 'None' %>
    <pre><code class="nohighlight"><%= @post.text %></code></pre>
  <% elsif @post.lang == 'Other'%>
    <pre><code><%= @post.text %></code></pre>
  <%else%>
    <pre><code class="<%= @post.lang.downcase%>"><%= @post.text %></code></pre>
  <%end%>
</p>
<p>
  <% if current_user != nil and @post.user_id == current_user.id  %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} %>
  <% end %>
</p>
<hr>

<p>
  <b>Comments:</b>
</p>

<% @post.comments.each do |c|%>
  <p>
    <%= c.user.username %> said:
  </p>
  <p>
    <i><%= c.text %></i>
  </p>
  <hr />
<% end%>

<% if user_signed_in? %>
  <p>
    <i>Send comment</i>
  </p>

  <%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
      <%= f.text_area :text, :class => "form-control", :rows => "3"  %>
    </p>
    <p>
      <%= f.submit :class => "btn btn-primary btn-sm"  %>
    </p>
  <%end%>
<% else %>
  <b><%= link_to "Sign in", user_session_path %> or <%= link_to "register", new_user_registration_path %> to post comments</b>
<% end %>

app/views/profiles/index.html.erb
<h4>Users List:</h4>
<ul>
  <% @profiles.each do |p| %>
  <li>
      <b><%= link_to p.username, profile_path(p)%></b>
  </li>
  <% end %>
</ul>

app/views/profiles/show.html.erb
<h4>Name: <%= @profile.username %></h4>
<p>
  <i>registered in:
  <%= @profile.created_at.strftime("%Y-%m-%d")%></i>
</p>
<b><%= @profile.username %> posts:</b>
<div id="my-posts">
  <%= render @posts %>
</div>

<div id="infinite-scrolling">
  <%= will_paginate @posts %>
</div>
</p>